fos_user_resetting_request:
    path: /reinit
    defaults: { _controller: FOSUserBundle:Resetting:request }

fos_user_resetting_send_email:
    path: /envoi-email
    defaults: { _controller: FOSUserBundle:Resetting:sendEmail }

fos_user_resetting_check_email:
    path: /check-email
    defaults: { _controller: FOSUserBundle:Resetting:checkEmail }

fos_user_resetting_reset:
    path: /reset/{token}
    defaults: { _controller: FOSUserBundle:Resetting:reset }