SiadoBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: SiadoBundle\Repository\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
        date:
            type: datetime
        description:
            type: text
            length: 255
    oneToOne:
        image:
            targetEntity: Image
            cascade: [ persist, remove ]
    lifecycleCallbacks: {  }
