<?php

namespace SiadoBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getArticlesByDate($order){
        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.date', $order);
        return $qb->getQuery()->getResult();
    }

    public function getSomeArticlesByDate($order, $number){
        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.date', $order)->setMaxResults($number);
        return $qb->getQuery()->getResult();
    }

    public function getArticlesListe($first = 0, $max = 3){
        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.date', 'DESC')
            ->setFirstResult($first)
            ->setMaxResults($max);
        return $qb->getQuery()->getResult();
    }

    public function getAllArticleByDate($order){
        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.date', $order);
        return $qb->getQuery()->getResult();
    }

    public function getPreviousArticle($id)
    {
        $qb = $this->createQueryBuilder('a');

        return $qb->select('MIN(a.id)')
            ->where('a.id > :id')
            ->setParameter('id', $id)
            ->orderBy('a.date', 'DESC')
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function getNextArticle($id)
    {
        $qb = $this->createQueryBuilder('a');

        return $qb->select('MAX(a.id)')
            ->where('a.id < :id')
            ->setParameter('id', $id)
            ->orderBy('a.date', 'DESC')
            ->getQuery()
            ->getOneOrNullResult();
    }
}
