<?php

namespace SiadoBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMessagesByDate($order){
        $qb = $this->createQueryBuilder('m');
        $qb->orderBy('m.id', $order);
        return $qb->getQuery()->getResult();
    }

    public function getRecentMessages(){
        $qb = $this->createQueryBuilder('m');
        $qb->where('m.status = :s')
            ->setParameter('s', 0)
            ->orderBy('m.id', 'ASC');
        return $qb->getQuery()->getResult();
    }
}
